CREATE TABLE SHTBOARD
(
      SUBJECTCODE      NUMBER         NOT NULL
	, TRADENO          NUMBER         NOT NULL
    , TRADESTATUS      NUMBER         NOT NULL        
	, TITLE            VARCHAR2(30)   NOT NULL
	, CONTENT          VARCHAR2(3000) NOT NULL
	, WRITEREMAIL      VARCHAR2(50)   NOT NULL
	, CREATEDATE       DATE           DEFAULT SYSDATE
);

-- add constraint 제약조건이름 제약조건 (컬럼명)
ALTER TABLE SHTBOARD ADD CONSTRAINT SHTBOARD_PK_COMPOUND PRIMARY KEY(subjectCode, tradeNo);

CREATE SEQUENCE SHTBOARD_TRADENO_SEQ
START   WITH 1
INCREMENT BY 1
;