CREATE TABLE SHTREPLY
(
    TRADENO     NUMBER         NOT NULL
  , REPNO       NUMBER         NOT NULL
  , CONTENT     VARCHAR2(1500) NOT NULL
  , REPLYWRITER VARCHAR2(50)   NOT NULL
  , CREATEDATE  DATE           DEFAULT SYSDATE
);

ALTER TABLE SHTREPLY ADD CONSTRAINT SHTREPLY_PK_COMPOUND PRIMARY KEY(TRADENO, REPNO);

CREATE SEQUENCE SHTREPLY_REPNO_SEQ
START   WITH 1
INCREMENT BY 1
;